version: '3.8'

services:
  postgres:
    container_name: api-find-a-friends
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=findafriends
      - PGDATA=/data/postgres

    volumes:
      - ./data/pg:/data/postgres
